name: Build WordPress Plugin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=dev" >> $GITHUB_OUTPUT
          fi
      
      - name: Create ZIP file
        run: |
          mkdir -p wordpress/plugin/licenses
          # Copy plugin files, excluding the wordpress directory and other unnecessary files
          rsync -av --exclude='wordpress' --exclude='.git*' . wordpress/plugin/licenses/
          cd wordpress/plugin
          zip -r licenses-${{ steps.get_version.outputs.version }}.zip licenses/
      
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: licenses-${{ steps.get_version.outputs.version }}
          path: wordpress/plugin/licenses-${{ steps.get_version.outputs.version }}.zip
      
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wordpress/plugin/licenses-${{ steps.get_version.outputs.version }}.zip
