name: Build WordPress Plugin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create ZIP file
        run: |
          cd wordpress/plugin
          zip -r ../../licenses.zip licenses/
      
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: licenses
          path: licenses.zip
      
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: licenses.zip
